name: docker containers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: "Docker"
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - run: |
          echo $MONDEY_DOCKER_IMAGE_TAG
          docker compose build
          docker compose push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          MONDEY_DOCKER_IMAGE_TAG: ${{ github.sha }}
      - run: |
          echo $MONDEY_DOCKER_IMAGE_TAG
          docker compose build
          docker compose push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          MONDEY_DOCKER_IMAGE_TAG: "latest"
